import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ne";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.packages": "Packages",
    "nav.contact": "Contact",
    "nav.free_consultation": "Get Free Consultation",
    "nav.direct_line": "Direct Line",
    "nav.consult_btn": "Consult",

    // Hero
    "hero.badge": "Supported by 30+ Years of Construction Experience through Prakash Nirman Sewa",
    "hero.headline_1": "Engineering Excellence.",
    "hero.headline_2": "Construction You Can Trust.",
    "hero.p1": "We deliver custom, earthquake-resilient building construction and professional engineering services across Nepal. By integrating rigorous structural analysis with decades of practical building experience, we guarantee that your architectural design translates into a flawless, high-durability structure on the ground.",
    "hero.p2": "From digital municipality clearance (e-BPS) to advanced structural drafting and continuous on-site civil supervision, our synchronized team coordinates every phase of your build. We manage timelines, control budgets, and eliminate middleman errors so you can build with complete peace of mind.",
    "hero.btn_consult": "Get Free Consultation",
    "hero.btn_projects": "View Our Projects",
    "hero.metric_1_title": "NBC-105 SECURE",
    "hero.metric_1_desc": "Earthquake resilient structural designs",
    "hero.metric_2_title": "e-BPS INTEGRATION",
    "hero.metric_2_desc": "Fast-track digital municipal clearance",
    "hero.metric_3_title": "ZERO SUBCONTRACTS",
    "hero.metric_3_desc": "No freelance middleman errors",
    "hero.floating_card_1_title": "NBC Approved",
    "hero.floating_card_1_desc": "Seismic structural dynamic simulations with high-ductility Fe 500D steel.",
    "hero.floating_card_2_title": "Integrated Build",
    "hero.floating_card_2_desc": "Designers and builders working in a single, unified workflow loop.",

    // Trust Strip
    "trust.years": "30+ Years",
    "trust.years_desc": "Construction Experience",
    "trust.warranty": "3-Year Structural",
    "trust.warranty_desc": "Written Warranty",
    "trust.approved": "e-BPS Approved",
    "trust.approved_desc": "Municipal Liaison",
    "trust.structural": "100% NBC-105",
    "trust.structural_desc": "Seismic Compliance",

    // Construction
    "construction.primary_ops": "PRIMARY CORE OPERATIONS",
    "construction.turnkey_title": "Turnkey Physical Execution",
    "construction.turnkey_desc": "We assume full structural and logistical liability—managing raw materials, excavation depth, foundation tie-bars, and premium finishing.",
    "construction.spec1": "Direct sourcing of verified Fe500D steel & national OPC cements",
    "construction.spec2": "Rigorous testing of soil, cement, and structural materials whenever required to ensure absolute safety before proceeding",
    "construction.spec3": "On-site licensed civil engineers supervising every beam-column junction pour",
    "construction.pricing_title": "PRICING INTEGRITY GUARANTEE:",
    "construction.pricing_desc": "We reject arbitrary per-square-foot ballpark quotes that hide structural variations. We calculate realistic item-wise Bills of Quantities directly from final structural designs.",
    "construction.contracts": "BUILDING CONTRACTS",
    "construction.eng_quality_title": "Engineering-Directed Construction Quality",
    "construction.eng_quality_desc": "In Nepal's high-seismic environment, structural execution cannot be left to unsupervised labor crews. At P.B. Consultation, we maintain direct engineering authority over all civil works. Our design engineers coordinate directly with site managers from day one, preventing structural interpretation errors during excavation, reinforcement, and concreting.",
    "construction.mat_sourcing_title": "Rigid Material Sourcing",
    "construction.mat_sourcing_desc": "We source high-ductility steel and high-grade cements from accredited national plants. We perform slump tests on-site and send concrete core samples to independent labs to ensure compressive design strength.",
    "construction.quality_log_title": "Continuous Quality Log",
    "construction.quality_log_desc": "A dedicated site engineer inspects critical milestones like foundation rebar tying, column junctions, and slab casting. Clients receive weekly digital photologs and milestone progress sheets.",
    "construction.btn_estimate": "Get Turnkey Estimate",
    "construction.learn_legacy": "Learn About Our Legacy",

    // Why Choose Us
    "why.org_identity": "ORGANIZATIONAL IDENTITY",
    "why.title_1": "Two Professional Divisions.",
    "why.title_2": "One Coordinated Vision.",
    "why.desc1": "P.B. Consultation Pvt. Ltd. was established in 2080 B.S. to deliver highly integrated structural engineering and architectural planning across Nepal.",
    "why.desc2": "To guarantee that our complex structural designs are perfectly buildable on site, we coordinate construction directly with our associated division: Prakash Nirman Sewa, which carries over 30 years of continuous practical field experience in Nepal.",
    "why.benefit_title": "THE DIRECT CLIENT BENEFIT",
    "why.benefit_desc": "Design engineers and building crews work together in a single loop. No structural translation mistakes. No finger-pointing. Traditional site delays and architectural errors are cut by up to 90%.",
    "why.workflow_title": "THE PB INTEGRATED WORKFLOW",
    "why.workflow_desc": "Unlike typical design studios, we oversee blueprint, permit, and physical masonry together.",
    "why.box1_title": "P.B. Consultation",
    "why.box1_subtitle": "Engineering & Design",
    "why.box1_f1": "NBC-105 compliant earthquake structural designs",
    "why.box1_f2": "Digital e-BPS municipal files & permit liaison",
    "why.box1_f3": "Precise structural steel detailing plans",
    "why.box1_f4": "Vastu Shastra integrated spatial planning",
    "why.box2_title": "Prakash Nirman Sewa",
    "why.box2_subtitle": "Construction Execution",
    "why.box2_f1": "30+ years of local execution experience",
    "why.box2_f2": "Direct heavy machinery & material logistics",
    "why.box2_f3": "Licensed on-site masons & carpenters",
    "why.box2_f4": "Turnkey Vastu-aligned layout execution",
    "why.bottom_text": "Planning a modern residence or a commercial build? Ensure your safety by bringing our joint engineering committee on board.",
    "why.bottom_cta": "Consult with our joint technical team",

    // Process
    "process.heading": "OUR DETAILED METHODOLOGY",
    "process.title": "Engineering-First Milestones",
    "process.desc": "We follow a highly transparent, engineering-driven process to transform empty plots into structurally secure, premium completed spaces.",
    "process.step1_num": "01",
    "process.step1_title": "Structural & Architectural Planning",
    "process.step1_desc": "We prepare detailed 2D architectural floor plans, 3D walkthrough renderings, and highly compliant NBC-105 structural calculations.",
    "process.step2_num": "02",
    "process.step2_title": "e-BPS Municipal File Submission",
    "process.step2_desc": "Our licensed engineers generate and submit all required municipal clearance digital drawings to e-BPS, managing permits seamlessly.",
    "process.step3_num": "03",
    "process.step3_title": "BOQ Sourcing & Structural Steel Detailing",
    "process.step3_desc": "We calculate a granular, transparent Bill of Quantities (BOQ). We order Fe500D premium steel and structural cements directly from national factories.",
    "process.step4_num": "04",
    "process.step4_title": "Rigid Site Supervision & Quality Concrete Pour",
    "process.step4_desc": "We inspect rebar layout, perform on-site concrete slump tests, and document compression strength lab reports for every major column & beam pour.",

    // Services
    "services.heading": "OUR PROFESSIONAL SERVICES",
    "services.title": "Specialized Engineering & Architecture",
    "services.desc": "We deliver a comprehensive suite of professional design and municipal services across Nepal.",
    "services.tagline_arch": "Integrated Design",
    "services.title_arch": "Architectural Design & Vastu",
    "services.desc_arch": "Bespoke, climate-responsive layouts optimized for ventilation, natural light, and strict local setback guidelines, while fully honoring traditional Vastu Shastra principles.",
    "services.tagline_struct": "NBC Compliant",
    "services.title_struct": "Structural Design",
    "services.desc_struct": "Seismic engineering compliant with the National Building Code (NBC-105). Includes finite-element dynamic analysis and safe column-beam ductile detailing.",
    "services.tagline_bps": "Licensed Submission",
    "services.title_bps": "Municipality Approval (e-BPS)",
    "services.desc_bps": "End-to-end processing and complete structural submission documentation for e-BPS municipal clearance, preventing long delays.",
    "services.badge_bps": "Available within Kathmandu Valley only.",
    "services.tagline_interior": "Bespoke Finishes",
    "services.title_interior": "Premium Interior Design",
    "services.desc_interior": "High-end indoor space planning, lighting designs, acoustic layouts, custom cabinetry, and bespoke wood and stone joinery.",
    "services.tagline_retro": "Structural Strengthening",
    "services.title_retro": "Renovation & Retrofitting",
    "services.desc_retro": "Structural retrofitting and structural strengthening designs to upgrade existing buildings to modern earthquake resistance.",
    "services.tagline_supervision": "Engineering Assurance",
    "services.title_supervision": "Construction Supervision",
    "services.desc_supervision": "Rigorous checklist-driven milestone inspections covering foundation steel layout, frame alignment, and raw concrete pours.",

    // Projects
    "projects.heading": "FEATURED PROJECTS",
    "projects.title": "Selected Projects. Built for the Long Term.",
    "projects.desc": "From modern family residences to premium bungalows and commercial buildings, every project is designed with structural safety, practical planning, and long-term durability in mind.",
    "projects.owner": "Property Owner",
    "projects.built_area": "Built-Up Area",
    "projects.land_area": "Land Area",
    "projects.status": "Status",
    "projects.engineering_title": "PROJECT OVERVIEW",
    "projects.highlights_title": "Project Highlights",
    "projects.specifications": "Material Specifications",
    "projects.cement": "Cement",
    "projects.steel": "Steel",
    "projects.concrete": "Concrete Grade",
    "projects.testimonial_title": "CLIENT TESTIMONIAL",

    // Project Details
    "project.balaram.title": "Project Dhapasi Height, Tokha",
    "project.balaram.location": "Tokha, Kathmandu",
    "project.balaram.status": "Completed",
    "project.balaram.builtUpArea": "4,200 Sq. Ft.",
    "project.balaram.landArea": "12 Aana",
    "project.balaram.focus": "Advanced soil-structure interaction, dual system design with RC shear walls + moment-resisting frames for ultimate earthquake resilience in deep Kathmandu valley soil, featuring full North-East facing Vastu compliance.",
    "project.balaram.f1": "Rigid shear wall seismic design (NBC-105 compliant)",
    "project.balaram.f2": "Traditional brick veneer exterior detailing",
    "project.balaram.f3": "Soundproofing double glazed low-E glass windows",
    "project.balaram.cement": "OPC 53 Grade (Jagadamba)",
    "project.balaram.steel": "Fe 500D High-Ductility (Ambe)",
    "project.balaram.concrete": "M25 (Foundations & Columns)",
    "project.balaram.feedback": "P.B. Consultation made our municipal permit approval seamless. Their high structural standards and Vastu alignment gave our family absolute safety and spiritual confidence.",

    "project.shanta.title": "Project Bafal, Nagarjun",
    "project.shanta.location": "Nagarjun, Kathmandu",
    "project.shanta.status": "Structure Stage",
    "project.shanta.builtUpArea": "3,850 Sq. Ft.",
    "project.shanta.landArea": "5.5 Aana",
    "project.shanta.focus": "Deep basement retaining wall calculations, contiguous pile integration, and specialized structural detailing for safe vertical excavation on narrow plots. Vastu-compliant kitchen and bedroom placement.",
    "project.shanta.f1": "Deep basement excavation with micro-piling",
    "project.shanta.f2": "Seepage-proof tanking waterproofing system",
    "project.shanta.f3": "Precision structural framing alignment",
    "project.shanta.cement": "OPC 53 Grade (Shivam)",
    "project.shanta.steel": "Fe 500D TMT (Shaurya)",
    "project.shanta.concrete": "M25 (Continuous Pour)",
    "project.shanta.feedback": "The team's daily on-site supervision and concrete tests during foundation pouring show they do not cut corners. Outstanding engineering and beautiful Vastu orientation.",

    "project.ganesh.title": "Project Khasibazar Kalanki, KMC",
    "project.ganesh.location": "Kalanki, Kathmandu",
    "project.ganesh.status": "Finishing Stage",
    "project.ganesh.builtUpArea": "5,100 Sq. Ft.",
    "project.ganesh.landArea": "8 Aana",
    "project.ganesh.focus": "Exterior rain envelope protection, structural frame analysis, and bespoke spatial layout optimization for heavy monsoon environments. Aligned with strict Vastu entrance orientations.",
    "project.ganesh.f1": "Heavy-duty clay brick exterior envelope",
    "project.ganesh.f2": "Optimized natural light and ventilation flow",
    "project.ganesh.f3": "Premium local granite stairs & flooring",
    "project.ganesh.cement": "OPC 53 Grade for frame, PPC for masonry",
    "project.ganesh.steel": "Fe 500D High-Ductility (Laxmi)",
    "project.ganesh.concrete": "M20 (High strength mix)",
    "project.ganesh.feedback": "Having a team that coordinates design directly with site execution crews made our home construction stress-free. Very professional management, completely respecting our Vastu preferences.",

    "project.kavresthali.title": "Project Kavresthali, Tarakeshwor",
    "project.kavresthali.location": "Tarakeshwor, Kathmandu",
    "project.kavresthali.status": "Structure Stage",
    "project.kavresthali.builtUpArea": "3,842 Sq. Ft.",
    "project.kavresthali.landArea": "7 Aana Plot",
    "project.kavresthali.focus": "Engineering-led residential construction situated on a 7 Aana sloping plot in Kavresthali, Tarakeshwor. Designed with deep foundation tie-beams, reinforced concrete retaining walls to resist hill-slope soil pressures, and a ductile moment-resisting RC frame adhering to NBC-105 earthquake codes. Incorporates North-East Vastu orientations.",
    "project.kavresthali.f1": "NBC-105 compliant earthquake-resilient frame design",
    "project.kavresthali.f2": "Retaining walls for hill-slope soil stability",
    "project.kavresthali.f3": "North-East Vastu layout with optimal solar light",
    "project.kavresthali.cement": "OPC 53 Grade (Shivam)",
    "project.kavresthali.steel": "Fe 500D High-Ductility (Ambe)",
    "project.kavresthali.concrete": "M25 (Foundations & Columns)",
    "project.kavresthali.feedback": "P.B. Consultation's structural design for our Kavresthali plot solved the hill-slope soil challenge seamlessly. Exceptional civil engineering.",

    "projects.view_archives": "View Project Stage Archives",
    "projects.stage_design": "1. Design Stage",
    "projects.stage_during": "2. During Construction",
    "projects.stage_after": "3. After Construction",
    "projects.stage_all": "All 3 Stages",

    // Testimonials Section
    "testimonials.heading": "VERIFIED CLIENT REVIEWS",
    "testimonials.title": "What Property Owners Say About Us",
    "testimonials.desc": "We build strong relationships along with durable foundations. Read experiences from our valued clients in Kathmandu, Lalitpur, and Pokhara.",

    // Packages Section
    "packages.heading": "HOME BUILDING OPTIONS",
    "packages.title": "Simple & Flexible Home Building Packages",
    "packages.desc": "Every family has different dreams and budgets. Here is a simple overview of how we help you build your home—we customize the design and materials completely around your choice during our consultation.",
    "packages.quote_lbl": "Customized to Your Budget & House Design",
    "packages.mat_title": "Structure & Core Materials",
    "packages.fin_title": "Finishing & Look",
    "packages.eng_title": "What's Included for Your Peace of Mind",
    "packages.mat_steel": "Steel & Rods",
    "packages.mat_cement": "Cement Quality",
    "packages.mat_bricks": "Wall Brickwork",
    "packages.mat_sand": "Sand & Stone",
    "packages.fin_flooring": "Flooring & Stairs",
    "packages.fin_doors": "Doors & Windows",
    "packages.fin_plumbing": "Bathroom & Plumbing",
    "packages.fin_electrical": "Lights & Wiring",
    "packages.fin_painting": "Wall Painting",
    "packages.btn_select": "Discuss Your Home Plan",

    "package.executive.name": "Standard Family Home",
    "package.executive.tagline": "A comfortable, safe, and budget-friendly home built with reliable materials—ideal for everyday family living.",
    "package.executive.summary_structure": "Strong earthquake-safe structure built with Nepal Standard (NS) certified cement, reliable steel rods, and A-grade bricks.",
    "package.executive.summary_finishes": "Clean modern floor tiles, durable wooden doors, bright UPVC windows, quality bathroom fittings, and long-lasting weatherproof paint.",
    "package.executive.mat.steel": "Trusted Nepal Standard (NS) earthquake-safe steel rods",
    "package.executive.mat.cement": "Standard high-strength cement for pillars, beams & walls",
    "package.executive.mat.bricks": "Good quality machine-made red bricks",
    "package.executive.mat.sand": "Clean washed sand and well-graded stone aggregates",
    "package.executive.fin.flooring": "Neat floor tiles in rooms and durable granite on stairs",
    "package.executive.fin.doors": "Strong wooden door frames with clean UPVC windows",
    "package.executive.fin.plumbing": "Reliable leak-proof water pipes and standard bathroom fittings",
    "package.executive.fin.electrical": "Safe fire-resistant copper wiring and modern switches",
    "package.executive.fin.painting": "Weather-protective outside paint and smooth washable inside paint",
    "package.executive.eng1": "Complete 2D room layout & 3D house design with Vastu guidance",
    "package.executive.eng2": "Full assistance with municipality drawing & permit approval",
    "package.executive.eng3": "Freedom to choose tiles, colors, and fittings as per your taste",
    "package.executive.eng4": "Regular site checkups by our engineers and supervisors",
    "package.executive.eng5": "Weekly photo & video updates of your house progress",

    "package.premium.name": "Premium Modern Home",
    "package.premium.tagline": "Designed for modern bungalows and upgraded residences with spacious layouts, finer finishes, and extra personal care.",
    "package.premium.summary_structure": "Extra-durable earthquake-resilient structure with top-grade steel, premium cement, and full dampness/waterproofing protection.",
    "package.premium.summary_finishes": "Upgraded marble or wood-style flooring, seasoned hardwood doors, sound-insulated windows, modern designer bathrooms, and luxury paints.",
    "package.premium.mat.steel": "Top-grade rust-resistant earthquake-safe steel rods",
    "package.premium.mat.cement": "Premium high-grade cement for maximum structural life",
    "package.premium.mat.bricks": "First-class heavy-duty bricks with heat & damp protection",
    "package.premium.mat.sand": "Double-washed fine sand and premium crushed stone",
    "package.premium.fin.flooring": "Premium marble, granite, or wooden parquet flooring options",
    "package.premium.fin.doors": "Seasoned hardwood doors and sound-reducing double-glass windows",
    "package.premium.fin.plumbing": "Modern concealed bathroom fittings and branded sanitaryware",
    "package.premium.fin.electrical": "Smart-home ready safe wiring with decorative lighting points",
    "package.premium.fin.painting": "Luxury stain-resistant interior finish & all-weather exterior coat",
    "package.premium.eng1": "Custom 3D exterior & interior design tailored to your lifestyle",
    "package.premium.eng2": "Complete Vastu planning and municipality permit handling",
    "package.premium.eng3": "Dedicated senior engineer supervision throughout construction",
    "package.premium.eng4": "Special waterproofing in bathrooms, terrace, and ground floor",
    "package.premium.eng5": "3-Year written peace-of-mind warranty backed by Prakash Nirman Sewa",

    // Contact Form
    "contact.heading": "GET A FREE CONSULTATION",
    "contact.title": "Let's Construct Your Future Safely",
    "contact.desc": "Speak directly with our senior structural engineers. Get an itemized estimate, e-BPS permit clearance consultation, or Vastu guidance for your project.",
    "contact.full_name": "Full Name",
    "contact.phone": "Phone Number",
    "contact.email": "Email Address",
    "contact.location": "Project Location",
    "contact.location_placeholder": "e.g. Baluwatar, Jhamsikhel, Pokhara",
    "contact.project_type": "Project Type",
    "contact.type_res": "Residential Building",
    "contact.type_comm": "Commercial Complex",
    "contact.type_renov": "Renovation & Retrofitting",
    "contact.type_design": "Only Engineering Design & e-BPS",
    "contact.requirements": "Requirements & Specifications",
    "contact.req_placeholder": "Describe your land area, preferred stories, Vastu requirements, or any structural questions you have...",
    "contact.vastu_label": "Include Vastu Shastra consultation & alignment for my property",
    "contact.submit": "Submit Consultation Request",
    "contact.submitting": "Submitting Request...",
    "contact.success_title": "Thank you!",
    "contact.success_desc": "Your request has been received. Our engineering committee will review your requirements and contact you within 24 hours.",

    // Footer
    "footer.desc": "Integrated engineering design and structural construction services. Hand-in-hand with Prakash Nirman Sewa (30+ Years of Field Excellence in Nepal).",
    "footer.quick_links": "Quick Navigation",
    "footer.corporate_offices": "Corporate Offices",
    "footer.kathmandu": "Kathmandu Office",
    "footer.kathmandu_addr": "Kathmandu-16, Banasthali, Nepal",
    "footer.pokhara": "Pokhara Office",
    "footer.pokhara_addr": "Ranipauwa Road, Pokhara-11, Kaski",
    "footer.registered": "Registered Entity",
    "footer.registered_desc": "P.B. Consultation Pvt. Ltd. (Reg. No. 320851/080/081)",
    "footer.rights": "All Rights Reserved.",
    "footer.licensed": "Licensed Structural Engineers & Class-A Contractors."
  },
  ne: {
    // Nav
    "nav.home": "गृहपृष्ठ",
    "nav.about": "हाम्रो बारेमा",
    "nav.services": "सेवाहरू",
    "nav.projects": "परियोजनाहरू",
    "nav.packages": "प्याकेजहरू",
    "nav.contact": "सम्पर्क",
    "nav.free_consultation": "निःशुल्क परामर्श लिनुहोस्",
    "nav.direct_line": "प्रत्यक्ष फोन",
    "nav.consult_btn": "परामर्श",

    // Hero
    "hero.badge": "प्रकाश निर्माण सेवा मार्फत ३०+ वर्षको गौरवशाली निर्माण अनुभवको साथ",
    "hero.headline_1": "इन्जिनियरिङ उत्कृष्टता।",
    "hero.headline_2": "विश्वासिलो र सुरक्षित निर्माण।",
    "hero.p1": "हामी नेपालभर भूकम्प प्रतिरोधात्मक भवन निर्माण र व्यावसायिक इन्जिनियरिङ सेवाहरू प्रदान गर्दछौं। दशकौंको व्यावहारिक अनुभव र कडा संरचनात्मक विश्लेषण (Structural Analysis) को संयोजन मार्फत हामी तपाईंको घरलाई बलियो र दीर्घकालीन बनाउने ग्यारेन्टी दिन्छौं।",
    "hero.p2": "डिजिटल नक्सा पास (e-BPS) देखि आधुनिक आर्किटेक्चरल डिजाइन र प्रत्यक्ष इन्जिनियरिङ सुपरीवेक्षणसम्म, हाम्रो दक्ष टोलीले निर्माणको हरेक चरणलाई सहज रूपमा व्यवस्थापन गर्दछ। हामी समयमै निर्माण सम्पन्न गर्ने र बजेट नियन्त्रण गर्ने कुरा सुनिश्चित गर्दछौं।",
    "hero.btn_consult": "निःशुल्क परामर्श लिनुहोस्",
    "hero.btn_projects": "हाम्रा परियोजनाहरू",
    "hero.metric_1_title": "NBC-105 सुरक्षित",
    "hero.metric_1_desc": "भूकम्प प्रतिरोधात्मक विशेष इन्जिनियरिङ डिजाइन",
    "hero.metric_2_title": "e-BPS प्रक्रिया",
    "hero.metric_2_desc": "छिटो-छरितो सरकारी नक्सा पास प्रक्रिया",
    "hero.metric_3_title": "बिचौलिया रहित",
    "hero.metric_3_desc": "प्रत्यक्ष सुपरीवेक्षण र त्रुटिरहित निर्माण",
    "hero.floating_card_1_title": "NBC मापदण्ड स्वीकृत",
    "hero.floating_card_1_desc": "उच्च गुणस्तरको Fe 500D फलाम र भूकम्पिय लोड गणना।",
    "hero.floating_card_2_title": "एकीकृत निर्माण",
    "hero.floating_card_2_desc": "डिजाइनर र निर्माण टोलीको प्रत्यक्ष समन्वय र सहकार्य।",

    // Trust Strip
    "trust.years": "३०+ वर्ष",
    "trust.years_desc": "निर्माण कार्यको अनुभव",
    "trust.warranty": "३-वर्ष संरचनात्मक",
    "trust.warranty_desc": "लिखित वारेन्टी कार्ड",
    "trust.approved": "e-BPS स्वीकृत",
    "trust.approved_desc": "नगरपालिका नक्सा पास",
    "trust.structural": "१००% NBC-105",
    "trust.structural_desc": "भूकम्पिय सुरक्षा मापदण्ड",

    // Construction
    "construction.primary_ops": "हाम्रो मुख्य सेवा",
    "construction.turnkey_title": "पूर्ण निर्माण जिम्मेवारी (Turnkey Construction)",
    "construction.turnkey_desc": "हामी जग खन्ने कार्य, फलामको गुणस्तर, कंक्रिटिङ र उत्कृष्ट फिनिसिङ सम्मका सम्पूर्ण कार्यहरू प्राविधिक दायित्व सहित आफैं सम्पन्न गर्छौं।",
    "construction.spec1": "प्रमाणित Fe500D फलाम र उच्च स्तरको OPC सिमेन्टको प्रयोग",
    "construction.spec2": "आवश्यकता अनुसार माटो तथा अन्य निर्माण सामग्रीहरूको प्रयोगशाला परीक्षण (Lab Tests) गरी पूर्ण सुरक्षित र ढुक्क भएपछि मात्र काम अघि बढाउने सुनिश्चितता",
    "construction.spec3": "लाइसेन्स प्राप्त सिभिल इन्जिनियरद्वारा डन्डी बाँध्ने र ढलानको प्रत्यक्ष सुपरीवेक्षण",
    "construction.pricing_title": "बजेटको विश्वसनीयता ग्यारेन्टी:",
    "construction.pricing_desc": "हामी हचुवाको भरमा स्क्वायर फिटको आधारमा मूल्य तोकेर ग्राहकलाई भ्रममा राख्दैनौं। हामी पूर्ण इस्टिमेट र BOQ को आधारमा स्पष्ट र पारदर्शी लागत गणना गर्छौं।",
    "construction.contracts": "निर्माण सम्झौता",
    "construction.eng_quality_title": "इन्जिनियरिङ निर्देशित उच्च गुणस्तर",
    "construction.eng_quality_desc": "नेपाल जस्तो भूकम्पको उच्च जोखिम भएको देशमा भवन निर्माणको कार्य विना-प्राविधिक मिस्त्री वा कामदारको भरमा छोड्नु हुँदैन। P.B. Consultation मा हामी हरेक निर्माण कार्यमा प्रत्यक्ष इन्जिनियरको नेतृत्व सुनिश्चित गर्छौं। हाम्रा डिजाइन इन्जिनियरहरू र साइट म्यानेजरहरू पहिलो दिनदेखि नै सँगै काम गर्ने हुँदा डन्डी र ढलानमा कुनै प्राविधिक त्रुटि हुन पाउँदैन।",
    "construction.mat_sourcing_title": "सख्त सामग्री छनोट",
    "construction.mat_sourcing_desc": "हामी देशका उत्कृष्ट फ्याक्ट्रीहरूबाट उत्पादित उच्च लचकता भएका डन्डी र ५३ ग्रेडको सिमेन्ट मात्र प्रयोग गर्छौं। कंक्रिटको गुणस्तर मापन गर्न निरन्तर परीक्षणहरू गरिन्छ।",
    "construction.quality_log_title": "गुणस्तरको नियमित अभिलेख",
    "construction.quality_log_desc": "हाम्रा साइट इन्जिनियरले जग खन्ने, डन्डी बाँध्ने र ढलान गर्ने प्रत्येक महत्वपूर्ण चरणको चेकलिस्ट भर्छन्। विदेश वा टाढा रहनुभएका घरधनीहरूलाई हरेक हप्ता तस्बिर र भिडियो सहितको प्रगति विवरण पठाइन्छ।",
    "construction.btn_estimate": "पूर्ण अनुमान लागत लिनुहोस्",
    "construction.learn_legacy": "हाम्रो इतिहास बुझ्नुहोस्",

    // Why Choose Us
    "why.org_identity": "हाम्रो परिचय",
    "why.title_1": "दुई व्यावसायिक विभाग।",
    "why.title_2": "एउटै एकीकृत लक्ष्य।",
    "why.desc1": "P.B. Consultation Pvt. Ltd. को स्थापना नेपालभर व्यावसायिक संरचनात्मक इन्जिनियरिङ र सुरक्षित घरको नक्सांकन सेवा प्रदान गर्न वि.सं. २०८० मा भएको हो।",
    "why.desc2": "हाम्रा जटिल संरचनात्मक डिजाइनहरू मैदानमा हुबहु र सुरक्षित रूपमा लागू होस् भन्नका लागि हामी ३०+ वर्ष लामो व्यावहारिक क्षेत्र अनुभव बोकेको हाम्रो भगिनी संस्था प्रकाश निर्माण सेवासँग पूर्ण समन्वयमा निर्माण कार्य गर्दछौं।",
    "why.benefit_title": "ग्राहकले पाउने प्रत्यक्ष फाइदा",
    "why.benefit_desc": "डिजाइन इन्जिनियर र निर्माण टोलीले एउटै युनिटको रूपमा काम गर्छन्। यसले गर्दा ड्रइङ बुझ्नमा कुनै गल्ती हुँदैन, र निर्माण कार्यमा हुनसक्ने ढिलाइ र प्राविधिक गल्तीहरू ९०% सम्म कम हुन्छन्।",
    "why.workflow_title": "हाम्रो एकीकृत कार्यप्रणाली",
    "why.workflow_desc": "साधारण कन्सल्टेन्सीहरू जस्तो नभई हामी नक्सांकन, नक्सा पास र भौतिक निर्माण सबै कार्यहरू आफैं गर्छौं।",
    "why.box1_title": "P.B. Consultation",
    "why.box1_subtitle": "इन्जिनियरिङ र डिजाइन",
    "why.box1_f1": "भूकम्प प्रतिरोधी संरचना डिजाइन (NBC-105 मापदण्ड)",
    "why.box1_f2": "डिजिटल नक्सा पास (e-BPS) र सरकारी समन्वय",
    "why.box1_f3": "डन्डीको काट्ने र बाँध्ने विस्तृत ड्रइङ (Detailing)",
    "why.box1_f4": "वास्तु शास्त्र र प्राकृतिक प्रकाशको पूर्ण समायोजन",
    "why.box2_title": "Prakash Nirman Sewa",
    "why.box2_subtitle": "भौतिक निर्माण कार्य",
    "why.box2_f1": "३०+ वर्ष लामो स्थानीय निर्माण र फिल्ड अनुभव",
    "why.box2_f2": "आवश्यक यन्त्र-उपकरण र निर्माण सामग्रीको प्रत्यक्ष व्यवस्थापन",
    "why.box2_f3": "दक्ष तथा लाइसेन्स प्राप्त डकर्मी र सिकर्मीहरू",
    "why.box2_f4": "वास्तु अनुसारको जग र कोठाहरूको भौतिक निर्माण",
    "why.bottom_text": "के तपाईं नयाँ र सुरक्षित घर वा व्यावसायिक भवन बनाउने सोचमा हुनुहुन्छ? हाम्रो संयुक्त प्राविधिक टोलीसँग परामर्श गर्नुहोस्।",
    "why.bottom_cta": "हाम्रो संयुक्त टोलीसँग परामर्श गर्नुहोस्",

    // Process
    "process.heading": "हाम्रो कार्यप्रणाली",
    "process.title": "चरणबद्ध निर्माण प्रक्रिया",
    "process.desc": "हामी खाली जग्गालाई सुरक्षित, सुन्दर र व्यवस्थित घरमा रूपान्तरण गर्न इन्जिनियरिङ-निर्देशित पारदर्शी विधिहरू पालना गर्छौं।",
    "process.step1_num": "०१",
    "process.step1_title": "आर्किटेक्चरल नक्सा र भूकम्प प्रतिरोधी डिजाइन",
    "process.step1_desc": "तपाईंको आवश्यकता अनुसार २D कोठाको लेआउट, ३D भिडियो र नेपाल सरकारको भवन संहिता (NBC-105) अनुसारको बलियो संरचनात्मक डिजाइन तयार गर्छौं।",
    "process.step2_num": "०२",
    "process.step2_title": "e-BPS नगरपालिका नक्सा पास",
    "process.step2_desc": "हाम्रा लाइसेन्स प्राप्त इन्जिनियरहरूले नगरपालिकाको अनलाइन नक्सा पास प्रणाली (e-BPS) मा सम्पूर्ण आवश्यक कागजात बुझाएर नक्सा पासको काम सजिलै सम्पन्न गर्छन्।",
    "process.step3_num": "०३",
    "process.step3_title": "विस्तृत लागत (BOQ) र निर्माण सामग्री व्यवस्थापन",
    "process.step3_desc": "हामी निर्माण सामग्रीको विस्तृत सूचि र पारदर्शी लागत अनुमान (BOQ) तयार गर्छौं, र उत्कृष्ट फ्याक्ट्रीबाट सीधै गुणस्तरीय सिमेन्ट र फलाम खरिद गर्छौं।",
    "process.step4_num": "०४",
    "process.step4_title": "कडा इन्जिनियर सुपरीवेक्षण र गुणस्तरीय ढलान",
    "process.step4_desc": "हाम्रो टोलीले जग खन्दा, डन्डी बाँध्दा र कंक्रिट ढलान गर्दा आफैं उपस्थित भई गुणस्तर जाँच र कम्प्रेसन परीक्षण सुनिश्चित गर्दछ।",

    // Services
    "services.heading": "हाम्रा व्यावसायिक सेवाहरू",
    "services.title": "विशिष्ट इन्जिनियरिङ तथा आर्किटेक्चर",
    "services.desc": "हामी नेपालभर व्यावसायिक डिजाइन, सरकारी नक्सा पास र भौतिक निर्माण सेवाहरू प्रदान गर्दछौं।",
    "services.tagline_arch": "एकीकृत डिजाइन",
    "services.title_arch": "आर्किटेक्चरल डिजाइन र वास्तु शास्त्र",
    "services.desc_arch": "नेपालको हावापानी सुहाउँदो र नगरपालिकाको मापदण्ड अनुसार कोठाहरूमा उज्यालो र हावाको बहाव मिलाई परम्परागत वास्तु शास्त्र अनुसारको उत्कृष्ट नक्सा डिजाइन।",
    "services.tagline_struct": "NBC मापदण्ड स्वीकृत",
    "services.title_struct": "भूकम्प प्रतिरोधी संरचनात्मक डिजाइन (Structural Design)",
    "services.desc_struct": "राष्ट्रिय भवन संहिता (NBC-105) अनुरुप भूकम्प प्रतिरोधात्मक क्षमता सुनिश्चित गर्न सफ्टवेयर मोडलिङ र विस्तृत इन्जिनियरिङ ड्रइङ।",
    "services.tagline_bps": "लाइसेन्स प्राप्त प्रक्रिया",
    "services.title_bps": "नगरपालिका नक्सा पास (e-BPS)",
    "services.desc_bps": "नगरपालिकाको अनलाइन नक्सा पास प्रणाली (e-BPS) को लागि आवश्यक सबै प्राविधिक कागजात र इन्जिनियरिङ सहिछाप सहित सहज नक्सा पास सेवा।",
    "services.badge_bps": "काठमाडौं उपत्यकाभित्र मात्र उपलब्ध।",
    "services.tagline_interior": "उत्कृष्ट फिनिसिङ",
    "services.title_interior": "प्रिमियम इन्टेरियर डिजाइन (Interior Design)",
    "services.desc_interior": "घरभित्रको खाली भागलाई सजाउने, फोल्स सिलिङ, आधुनिक लाइटिङ, गुणस्तरीय क्याबिनेट र आकर्षक फर्निचर सजावटको विस्तृत काम।",
    "services.tagline_retro": "संरचना सुदृढीकरण",
    "services.title_retro": "मर्मत सम्भार र रेट्रोफिटिङ (Retrofitting)",
    "services.desc_retro": "पुराना वा भूकम्पले कमजोर बनाएका भवनहरूलाई आधुनिक प्रविधि र थप फलामको फ्रेम प्रयोग गरी पुनः बलियो र सुरक्षित बनाउने काम।",
    "services.tagline_supervision": "प्राविधिक सुरक्षा ग्यारेन्टी",
    "services.title_supervision": "निर्माण सुपरीवेक्षण (Supervision)",
    "services.desc_supervision": "डन्डीको दुरी, फर्माको जग र कंक्रिटको मिश्रण सही छ छैन भनी निर्माण स्थलमै इन्जिनियर खटाएर गरिने कडा प्राविधिक सुपरीवेक्षण।",

    // Projects
    "projects.heading": "विशेष परियोजनाहरू",
    "projects.title": "दीर्घकालीन र सुरक्षित निर्माणका उत्कृष्ट उदाहरणहरू",
    "projects.desc": "आधुनिक आवासीय घर देखि लिएर प्रिमियम बंगला र व्यावसायिक भवनहरू सम्म, हामीले निर्माण गरेका हरेक संरचनाहरू भूकम्पिय सुरक्षा र वास्तु अनुसार बनेका छन्।",
    "projects.owner": "घरधनी",
    "projects.built_area": "कुल क्षेत्रफल",
    "projects.land_area": "जग्गाको क्षेत्रफल",
    "projects.status": "अवस्था",
    "projects.engineering_title": "परियोजना विवरण",
    "projects.highlights_title": "मुख्य विशेषताहरू",
    "projects.specifications": "निर्माण सामग्रीको विवरण",
    "projects.cement": "सिमेन्ट",
    "projects.steel": "डन्डी (फलाम)",
    "projects.concrete": "कंक्रिट ग्रेड",
    "projects.testimonial_title": "ग्राहकको प्रतिक्रिया",

    // Project Details
    "project.balaram.title": "प्रोजेक्ट धापासी हाइट, टोखा",
    "project.balaram.location": "टोखा, काठमाडौं",
    "project.balaram.status": "सम्पन्न भएको",
    "project.balaram.builtUpArea": "४,२०० वर्ग फिट",
    "project.balaram.landArea": "१२ आना",
    "project.balaram.focus": "गहिरो माटो सुहाउँदो जग डिजाइन, कडा भूकम्पिय लोड धान्नको लागि RC सियर वाल (Shear Wall) र फ्रेमको संयुक्त संरचना, उत्तर-पूर्व वास्तु मिलावट सहित पूर्ण रूपमा सुरक्षित आवास।",
    "project.balaram.f1": "सियर वाल भूकम्प प्रतिरोधी डिजाइन (NBC-105 अनुरुप)",
    "project.balaram.f2": "बाहिरी भागमा आकर्षक परम्परागत इँटा बुट्टाको काम",
    "project.balaram.f3": "ध्वनि नियन्त्रण गर्ने डबल-ग्लेज्ड कम-E सिसाको झ्याल",
    "project.balaram.cement": "OPC ५३ ग्रेड (जगदम्बा)",
    "project.balaram.steel": "Fe 500D उच्च लचकता भएको (अम्बे)",
    "project.balaram.concrete": "M25 (फाउन्डेसन र पिल्लर)",
    "project.balaram.feedback": "P.B. Consultation ले गर्दा नगरपालिकामा हाम्रो नक्सा सहजै पास भयो। उहाँहरूको कडा प्राविधिक मापदण्ड र वास्तु मिलावटले हाम्रो परिवारलाई पूर्ण सुरक्षा र सन्तुष्टि दिएको छ।",

    "project.shanta.title": "प्रोजेक्ट बाफल, नागार्जुन",
    "project.shanta.location": "नागार्जुन, काठमाडौं",
    "project.shanta.status": "स्ट्रक्चर चरण",
    "project.shanta.builtUpArea": "३,८५० वर्ग फिट",
    "project.shanta.landArea": "५.५ आना",
    "project.shanta.focus": "साँघुरो ठाउँमा सुरक्षित रूपमा बेसमेन्ट खन्न micro-piling प्रविधिको प्रयोग र ओसिलो रोक्न विशेष waterproofing सिस्टम। वास्तु अनुसार भान्सा र सुत्ने कोठाको लेआउट।",
    "project.shanta.f1": "माइक्रो-पाइलिङ सहितको गहिरो बेसमेन्ट उत्खनन",
    "project.shanta.f2": "ओसिलो र पानी चुहावट पूर्ण रूपमा रोक्ने वाटरप्रुफिङ",
    "project.shanta.f3": "सटीक फ्रेम पिल्लर एलाइनमेन्ट",
    "project.shanta.cement": "OPC ५३ ग्रेड (शिवम् सिमेन्ट)",
    "project.shanta.steel": "Fe 500D TMT (शौर्य)",
    "project.shanta.concrete": "M25 (कन्टिन्युअस कंक्रीट ढलान)",
    "project.shanta.feedback": "टोलीले जग ढलानको समयमा आफैं साइटमा बसी कंक्रिटको गुणस्तर र डन्डीको दुरी नापेको देख्दा उहाँहरूको इमानदारिता प्रमाणित हुन्छ। असाध्यै राम्रो इन्जिनियरिङ र वास्तु मिलावट।",

    "project.ganesh.title": "प्रोजेक्ट खसीबजार कलङ्की, केएमसी",
    "project.ganesh.location": "कलङ्की, काठमाडौं",
    "project.ganesh.status": "फिनिसिङ चरण",
    "project.ganesh.builtUpArea": "५,१०० वर्ग फिट",
    "project.ganesh.landArea": "८ आना",
    "project.ganesh.focus": "बाहिरी भित्ताको वर्षा सुरक्षा डिजाइन र पर्याप्त उज्यालो आउने ठूला झ्यालहरू। मुख्य प्रवेशद्वारको वास्तु दिशा मिलाइएको।",
    "project.ganesh.f1": "उच्च गुणस्तरको क्ले-ब्रिक बाहिरी गारो",
    "project.ganesh.f2": "प्राकृतिक उज्यालो र हावा आवतजावतको उत्तम प्रवाह",
    "project.ganesh.f3": "सिँढी र भुइँमा प्रिमियम लोकल ग्रेनाइट",
    "project.ganesh.cement": "पिल्लरको लागि OPC ५३ र गारोको लागि PPC सिमेन्ट",
    "project.ganesh.steel": "Fe 500D उच्च लचकता भएको (लक्ष्मी स्टील)",
    "project.ganesh.concrete": "M20 (उच्च शक्ति युक्त कंक्रिट मिश्रण)",
    "project.ganesh.feedback": "डिजाइन गर्ने कन्सल्टेन्सी र साइटमा काम गर्ने निर्माण टोली एउटै हुँदा हाम्रो घर निर्माण कार्य एकदमै तनावरहित र सहज भयो। वास्तु मिलाउनुका साथै उच्च कोटीको काम भएको छ।",

    "project.kavresthali.title": "प्रोजेक्ट काभ्रेस्थली, तारकेश्वर",
    "project.kavresthali.location": "तारकेश्वर, काठमाडौं",
    "project.kavresthali.status": "स्ट्रक्चर चरण",
    "project.kavresthali.builtUpArea": "३,८४२ वर्ग फिट",
    "project.kavresthali.landArea": "७ आना जग्गा",
    "project.kavresthali.focus": "तारकेश्वरको काभ्रेस्थलीमा ७ आना जग्गामा निर्माणाधीन आवासीय भवन। गहिरो फाउन्डेसन टाई-बीम, भीर-किरारा माटो सुरक्षाको लागि RC रिटेनिङ पर्खाल र NBC-105 भूकम्पिय सुरक्षा मापदण्ड अनुरुप वास्तु मिलाएर निर्माण भइरहेको।",
    "project.kavresthali.f1": "NBC-105 भूकम्प प्रतिरोधी संरचना फ्रेम",
    "project.kavresthali.f2": "भीर माटो सुरक्षाको लागि RC रिटेनिङ पर्खाल",
    "project.kavresthali.f3": "उत्तर-पूर्व वास्तु र सूर्यको प्रकाश मिलाइएको",
    "project.kavresthali.cement": "OPC ५३ ग्रेड (शिवम् सिमेन्ट)",
    "project.kavresthali.steel": "Fe 500D उच्च लचकता (अम्बे स्टील)",
    "project.kavresthali.concrete": "M25 (फाउन्डेसन र पिल्लर)",
    "project.kavresthali.feedback": "P.B. Consultation को संरचनात्मक डिजाइनले काभ्रेस्थलीको भीर जग्गामा निर्माण एकदमै सुरक्षित र भरपर्दो बनाइदियो।",

    "projects.view_archives": "परियोजनाका ३ वटै आर्काइभ चरणहरू हेर्नुहोस्",
    "projects.stage_design": "१. डिजाइन चरण",
    "projects.stage_during": "२. निर्माण भइरहँदा",
    "projects.stage_after": "३. निर्माण पश्चात (सम्पन्न)",
    "projects.stage_all": "३ वटै चरणहरू",

    // Testimonials Section
    "testimonials.heading": "प्रमाणित ग्राहक प्रतिक्रिया",
    "testimonials.title": "हाम्रा आदरणीय घरधनीहरूको अनुभव",
    "testimonials.desc": "हामी बलियो जग सँगसँगै अटुट सम्बन्ध पनि निर्माण गर्छौं। काठमाडौं, ललितपुर र पोखराका हाम्रा आदरणीय ग्राहकहरूको वास्तविक अनुभव यहाँ पढ्नुहोस्।",

    // Packages Section
    "packages.heading": "घर निर्माणका विकल्पहरू",
    "packages.title": "तपाईंको बजेट र आवश्यकता अनुसारको घर निर्माण",
    "packages.desc": "हरेक परिवारको चाहना र बजेट फरक हुन्छ। यहाँ हाम्रा सामान्य सेवाहरूको संक्षिप्त जानकारी दिइएको छ—प्रत्यक्ष सल्लाह र छलफल पछि तपाईंको रोजाइ अनुसार नै निर्माण सामग्री र डिजाइन तय गरिन्छ।",
    "packages.quote_lbl": "तपाईंको बजेट र घरको नक्सा अनुसार लचिलो मूल्य",
    "packages.mat_title": "जग, पिल्लर र मुख्य निर्माण सामग्री",
    "packages.fin_title": "फिनिसिङ र भित्री सजावट",
    "packages.eng_title": "हामीले प्रदान गर्ने मुख्य सहजता र सेवाहरू",
    "packages.mat_steel": "डन्डी (फलाम)",
    "packages.mat_cement": "सिमेन्ट",
    "packages.mat_bricks": "इँटा र गारो",
    "packages.mat_sand": "बालुवा र गिट्टी",
    "packages.fin_flooring": "भुइँ र सिँढी",
    "packages.fin_doors": "ढोका र झ्याल",
    "packages.fin_plumbing": "बाथरुम र धारा",
    "packages.fin_electrical": "बत्ती र वाइरिङ",
    "packages.fin_painting": "रङरोगन (पेन्ट्स)",
    "packages.btn_select": "घर निर्माणबारे सल्लाह लिनुहोस्",

    "package.executive.name": "सामान्य पारिवारिक घर (Standard Home)",
    "package.executive.tagline": "भरपर्दो निर्माण सामग्री र सुलभ बजेटमा बलियो, सुरक्षित तथा आरामदायी पारिवारिक घर बनाउनका लागि उपयुक्त।",
    "package.executive.summary_structure": "नेपाल गुणस्तर (NS) प्रमाणित सिमेन्ट, भरपर्दो डन्डी र एक नम्बर इँटा प्रयोग गरी बनाइने बलियो भूकम्प प्रतिरोधी संरचना।",
    "package.executive.summary_finishes": "कोठाहरूमा सफा र आकर्षक टायल, सिँढीमा ग्रेनाइट, बलिया काठका ढोका, उज्यालो UPVC झ्याल र टिकाउ रङरोगन।",
    "package.executive.mat.steel": "नेपाल गुणस्तर (NS) प्रमाणित भरपर्दो फलामको डन्डी",
    "package.executive.mat.cement": "ढलान र गारोका लागि उच्च गुणस्तरको प्रमाणित सिमेन्ट",
    "package.executive.mat.bricks": "राम्रो पाकेको एक नम्बर रातो इँटा",
    "package.executive.mat.sand": "सफा पखालेको बालुवा र गुणस्तरीय गिट्टी",
    "package.executive.fin.flooring": "कोठाहरूमा आकर्षक टायल र सिँढीमा बलियो ग्रेनाइट",
    "package.executive.fin.doors": "बलियो काठको चौकोस/ढोका र सफा UPVC झ्यालहरू",
    "package.executive.fin.plumbing": "पानी नचुहिने बलियो पाइप र भरपर्दो बाथरुम फिटिङ्स",
    "package.executive.fin.electrical": "सुरक्षित तामाको तार र आकर्षक आधुनिक स्विचहरू",
    "package.executive.fin.painting": "बाहिर घाम-पानी थेग्ने र भित्र सफा गर्न मिल्ने राम्रो रङ",
    "package.executive.eng1": "वास्तु मिलाएर २D कोठाको नक्सा र ३D घरको बाहिरी डिजाइन",
    "package.executive.eng2": "नगरपालिकामा नक्सा पास प्रक्रियाको लागि पूर्ण सहयोग",
    "package.executive.eng3": "तपाईंको आफ्नै रोजाइ अनुसार रङ, टायल र सामान छान्ने सुविधा",
    "package.executive.eng4": "हाम्रा इन्जिनियर र सुपरभाइजरद्वारा साइटमा नियमित रेखदेख",
    "package.executive.eng5": "घर बन्दै गर्दाको फोटो र भिडियो नियमित रूपमा पठाइने",

    "package.premium.name": "प्रिमियम आधुनिक घर (Premium Home)",
    "package.premium.tagline": "आकर्षक आधुनिक डिजाइन, फराकिलो कोठाहरू, उच्च स्तरको फिनिसिङ र विशेष सुविधा खोज्ने परिवारको लागि उपयुक्त।",
    "package.premium.summary_structure": "उच्च गुणस्तरको डन्डी तथा सिमेन्ट, अतिरिक्त मजबुत ढलान र ओसिलोपन रोक्ने पूर्ण वाटरप्रुफिङ प्रविधि सहितको निर्माण।",
    "package.premium.summary_finishes": "आकर्षक मार्बल वा काठको पार्केटिङ, सिजनिङ गरेको काठका ढोका, आवाज कम गर्ने झ्याल, आधुनिक बाथरुम र प्रिमियम रङरोगन।",
    "package.premium.mat.steel": "खिया नलाग्ने र उच्च लचकता भएको प्रिमियम डन्डी",
    "package.premium.mat.cement": "सम्पूर्ण ढलान र निर्माणमा प्रिमियम ग्रेडको सिमेन्ट",
    "package.premium.mat.bricks": "उच्च भार धान्ने एक नम्बर इँटा र तापक्रम सन्तुलित गारो",
    "package.premium.mat.sand": "प्रशोधित सफा बालुवा र उच्च स्तरको क्रसर गिट्टी",
    "package.premium.fin.flooring": "प्रिमियम मार्बल, ग्रेनाइट वा न्यानो काठको पार्केटिङ",
    "package.premium.fin.doors": "सिजनिङ गरेको साल/टिक काठका ढोका र डबल-सिसाको झ्याल",
    "package.premium.fin.plumbing": "आधुनिक कन्सिल्ड बाथरुम सिस्टम र प्रिमियम फिटिङ्स",
    "package.premium.fin.electrical": "आकर्षक डेकोरेटिभ लाइटिङ र स्मार्ट-होम मैत्री सुरक्षित वाइरिङ",
    "package.premium.fin.painting": "भित्तामा प्रिमियम लक्जरी पेन्ट र बाहिर विशेष मौसम सुरक्षा कोटिङ",
    "package.premium.eng1": "तपाईंको जीवनशैली सुहाउँदो विशेष ३D बाहिरी र भित्री डिजाइन",
    "package.premium.eng2": "पूर्ण वास्तु परामर्श र नगरपालिका नक्सा पासको सम्पूर्ण सहजीकरण",
    "package.premium.eng3": "सिनियर सिभिल इन्जिनियरद्वारा निर्माण कार्यको प्रत्यक्ष सुपरीवेक्षण",
    "package.premium.eng4": "बाथरुम, कौसी र जगमा पानी र ओसिलोपन रोक्ने विशेष वाटरप्रुफिङ",
    "package.premium.eng5": "प्रकाश निर्माण सेवाको तर्फबाट ३ वर्षको लिखित वारेन्टी र ढुक्कको सेवा",

    // Contact Form
    "contact.heading": "निःशुल्क परामर्श लिनुहोस्",
    "contact.title": "तपाईंको भविष्यको सुरक्षित घर निर्माण गरौं",
    "contact.desc": "हाम्रा सिनियर संरचना इन्जिनियरहरूसँग सीधै कुरा गर्नुहोस्। आफ्नो जग्गाको लागि इस्टिमेट, e-BPS नक्सा पास प्रक्रिया, वा वास्तु सम्बन्धी परामर्श प्राप्त गर्नुहोस्।",
    "contact.full_name": "पूरा नाम",
    "contact.phone": "फोन नम्बर",
    "contact.email": "इमेल ठेगाना",
    "contact.location": "परियोजना रहेको स्थान",
    "contact.location_placeholder": "जस्तै: बालुवाटार, झम्सिखेल, पोखरा आदि",
    "contact.project_type": "परियोजनाको प्रकार",
    "contact.type_res": "आवासीय भवन (घर)",
    "contact.type_comm": "व्यावसायिक भवन (कमर्सियल)",
    "contact.type_renov": "मर्मत सम्भार तथा रेट्रोफिटिङ",
    "contact.type_design": "नक्सा डिजाइन र e-BPS नक्सा पास मात्र",
    "contact.requirements": "आवश्यकता तथा विस्तृत विवरण",
    "contact.req_placeholder": "तपाईंको जग्गाको क्षेत्रफल, तलाको संख्या, वास्तु सम्बन्धी प्राथमिकता वा इन्जिनियरिङ सम्बन्धी प्रश्नहरू लेखन्होस्...",
    "contact.vastu_label": "मेरो घरको लागि वास्तु शास्त्र परामर्श तथा मिलावट समावेश गर्नुहोस्",
    "contact.submit": "परामर्शको लागि अनुरोध पठाउनुहोस्",
    "contact.submitting": "अनुरोध पठाइँदैछ...",
    "contact.success_title": "धन्यवाद!",
    "contact.success_desc": "तपाईंको अनुरोध प्राप्त भएको छ। हाम्रो प्राविधिक इन्जिनियर टोलीले यसलाई अध्ययन गरी २४ घण्टाभित्र सम्पर्क गर्नेछ।",

    // Footer
    "footer.desc": "एकीकृत इन्जिनियरिङ डिजाइन र भूकम्प प्रतिरोधी भवन निर्माण सेवा। ३०+ वर्षको गौरवशाली इतिहास बोकेको प्रकाश निर्माण सेवासँगको सहकार्यमा।",
    "footer.quick_links": "नेभिगेसन लिङ्कहरू",
    "footer.corporate_offices": "हाम्रा कार्यालयहरू",
    "footer.kathmandu": "काठमाडौं कार्यालय",
    "footer.kathmandu_addr": "काठमाडौं-१६, वनस्थली, नेपाल",
    "footer.pokhara": "पोखरा कार्यालय",
    "footer.pokhara_addr": "रानीपौवा रोड, पोखरा-११, कास्की",
    "footer.registered": "दर्ता विवरण",
    "footer.registered_desc": "पि.बि. कन्सल्टेन्सी प्रा. लि. (दर्ता नं. ३२०८५१/०८०/०८१)",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.licensed": "लाइसेन्स प्राप्त संरचना इन्जिनियरहरू र 'क' वर्गका निर्माण ठेकेदार।"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("pb_lang");
    return (saved === "ne" ? "ne" : "en") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("pb_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
